# Use Dependabot to update GitHub Actions and the Terraform modules on our examples
version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    # Check for updated GitHub Actions every week
    interval: "weekly"
